### ISSUE TITLE
not find train_supervised.py

### ISSUE THREAD

**Issue by t1804330987** [WojciechKoz/Dimma#1]
I don't know how to run this progrm,don't find train_supervised.py.

**Comment by WojciechKoz** [comment]
Hello, thanks for your interest in our work. The standard Dimma approach assumes first to train unsupervised (using artificially dimmed pairs) and later finetune the model in a supervised way (with real pairs). Please, keep in mind that skipping the unsupervised training might make a big difference when you have a small dataset with for example three training pairs. 
For the standard way, please see the section "Run the code" in readme.md.

However, if you want to skip the part with artificial pairs(it should be OK to do that for the full LOL dataset for instance), you can run just the finetune.py script alone. The only thing you need to do is to uncomment line 25 and comment line 26 in **finetune.py**, like that: 
```
model = LitDimma(config=cfg)
# model = LitDimma.load_from_checkpoint(cfg.model.checkpoint, config=cfg)
```
This will create a new instance of the network instead of loading the checkpoint from unsupervised training.

Also, make sure to have the right dataset in ./data folder and use the proper config - for the whole LOL dataset it will be
```
python finetune.py --config="configs/LOL/stage2/large-lol-ft.yaml"
```

Feel free to ask if you have any more questions or encounter further issues, I am happy to help you.

**Comment by cjl506** [comment]
> I don't know how to run this progrm,don't find train_supervised.py.
你好，你解决这个问题了吗，我也没有找到这个文件

**Comment by WojciechKoz** [comment]
Hi, now I spot the problem. In the readme there is a typo - it should not be train_supervised but train_unsupervised. The typo is fixed, sorry for the trouble, and thank you for pointing that out, and thanks for your interest in our work.
